# Generated by Django 5.2.9 on 2026-09-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/default.jpg', upload_to='profile_image'),
        ),
    ]
