# Generated by Django 5.2.9 on 2026-09-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='emial',
            new_name='email',
        ),
    ]
